"""
build_random_labels.py
======================
Create crater labels for images generated by random_render.py.

For each image in <batch>/img, this script uses:
- <batch>/npz/<stem>.npz   (per-pixel lat/lon maps)
- <batch>/json/<stem>.json (lat/lon ranges)
- crater catalogue (parquet with x_coord, y_coord, diam_km)

Outputs:
- <batch>/label/<stem>.txt          YOLO-like circle labels
- <batch>/label/<stem>.meta.json    explicit center/radius metadata
- <batch>/label/examples_3.png      figure with 3 annotated examples

YOLO-like line format (custom):
    class_id x_center_norm y_center_norm radius_norm radius_px radius_km

Notes:
- This is "YOLO-like" (center normalized), but not strict YOLO bbox format.
- Radius is included both in pixels and in real km as requested.
"""

import argparse
import json
import os
import sys

import cv2
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.patches import Circle
from scipy.spatial import cKDTree

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, SCRIPT_DIR)

from utils.geo import KM_PER_DEG_LAT, normalize_lon  # noqa: E402


def parse_args():
    p = argparse.ArgumentParser(
        description="Build crater labels for random_render outputs (YOLO-like circles)."
    )
    p.add_argument(
        "--batch",
        required=True,
        help="Random render output directory (contains img/, json/, npz/)",
    )
    p.add_argument(
        "--craters",
        default=os.path.join(SCRIPT_DIR, "craters_unified.parquet"),
        help="Path to crater catalogue parquet",
    )
    p.add_argument(
        "--min-diam",
        type=float,
        default=5.0,
        help="Minimum crater diameter in km (default: 5.0)",
    )
    p.add_argument(
        "--max-diam",
        type=float,
        default=80.0,
        help="Maximum crater diameter in km (default: 80.0)",
    )
    p.add_argument(
        "--class-id",
        type=int,
        default=0,
        help="Class id written in label lines (default: 0)",
    )
    p.add_argument(
        "--examples",
        type=int,
        default=3,
        help="Number of visual examples to plot at the end (default: 3)",
    )
    return p.parse_args()


def _shift_lon(lon_arr, center_lon):
    """Shift longitudes relative to center_lon, returning (-180, 180]."""
    return ((lon_arr - center_lon + 180.0) % 360.0) - 180.0


def build_pixel_tree(lat_map, lon_map):
    """
    Build KDTree over valid pixels in centred isometric coordinates.

    Returns:
        tree, rows_v, cols_v, center_lat, center_lon, cos_lat_c
    """
    valid = np.isfinite(lat_map) & np.isfinite(lon_map)
    rows_v, cols_v = np.where(valid)
    lats_px = lat_map[rows_v, cols_v]
    lons_px = lon_map[rows_v, cols_v]

    center_lat = float(np.nanmean(lat_map))
    center_lon = float(np.nanmean(lon_map))
    cos_lat_c = float(np.cos(np.radians(center_lat)))

    rel_lat = lats_px - center_lat
    rel_lon = _shift_lon(lons_px, center_lon) * cos_lat_c
    pts = np.column_stack([rel_lat, rel_lon])

    return cKDTree(pts), rows_v, cols_v, center_lat, center_lon, cos_lat_c


def crater_radius_pixels(diam_km, lat_map):
    """Approximate crater radius in pixels from image latitude span."""
    lat_valid = lat_map[np.isfinite(lat_map)]
    if lat_valid.size == 0:
        return 1

    lat_range_deg = float(lat_valid.max() - lat_valid.min())
    if lat_range_deg <= 0:
        return 1

    h = lat_map.shape[0]
    km_per_px = (lat_range_deg * KM_PER_DEG_LAT) / h
    return max(1, int(round((diam_km / 2.0) / km_per_px)))


def _prefilter_craters(craters_df, summary, min_diam_km, max_diam_km):
    """Fast geographic prefilter using JSON lat/lon ranges and diameter limits."""
    lat_min, lat_max = summary["lat_range"]
    lon_min, lon_max = summary["lon_range"]

    max_diam_deg = max_diam_km / KM_PER_DEG_LAT
    lat_lo = lat_min - max_diam_deg
    lat_hi = lat_max + max_diam_deg

    lon_360 = normalize_lon(craters_df["x_coord"].values)
    lat_in = (craters_df["y_coord"].values >= lat_lo) & (craters_df["y_coord"].values <= lat_hi)

    if lon_max >= lon_min:
        lon_lo = lon_min - max_diam_deg
        lon_hi = lon_max + max_diam_deg
        if lon_lo < 0:
            lon_in = (lon_360 >= lon_lo + 360.0) | (lon_360 <= lon_hi)
        elif lon_hi > 360:
            lon_in = (lon_360 >= lon_lo) | (lon_360 <= lon_hi - 360.0)
        else:
            lon_in = (lon_360 >= lon_lo) & (lon_360 <= lon_hi)
    else:
        lon_in = (lon_360 >= lon_min - max_diam_deg) | (lon_360 <= lon_max + max_diam_deg)

    diam = craters_df["diam_km"].values
    diam_in = (diam >= min_diam_km) & (diam <= max_diam_km)

    keep = lat_in & lon_in & diam_in
    subset = craters_df[keep].copy()
    subset["lon_360"] = lon_360[keep]
    return subset


def build_labels_for_image(img_path, npz_path, json_path, craters_df, class_id, min_diam_km, max_diam_km):
    """
    Return list of label dicts for one image.

    Each label contains center in px/normalized and radius in px/km.
    """
    with open(json_path) as f:
        summary = json.load(f)

    data = np.load(npz_path)
    lat_map = data["lat"]
    lon_map = data["lon"]

    h, w = lat_map.shape
    subset = _prefilter_craters(craters_df, summary, min_diam_km, max_diam_km)
    if subset.empty:
        return [], h, w

    valid_mask = np.isfinite(lat_map) & np.isfinite(lon_map)
    if not valid_mask.any():
        return [], h, w

    tree, rows_v, cols_v, center_lat, center_lon, cos_lat_c = build_pixel_tree(lat_map, lon_map)

    labels = []
    for _, row in subset.iterrows():
        lat_c = float(row["y_coord"])
        lon_c = float(row["lon_360"])
        diam_km = float(row["diam_km"])
        radius_km = diam_km / 2.0

        rel_lat = lat_c - center_lat
        rel_lon = _shift_lon(lon_c, center_lon) * cos_lat_c
        _, idx = tree.query([[rel_lat, rel_lon]], k=1)
        px_row = int(rows_v[idx[0]])
        px_col = int(cols_v[idx[0]])

        radius_px = crater_radius_pixels(diam_km, lat_map)
        x_center_n = (px_col + 0.5) / w
        y_center_n = (px_row + 0.5) / h

        # Use average image scale for normalized radius.
        radius_n = radius_px / float(max(w, h))

        labels.append(
            {
                "class_id": int(class_id),
                "x_center_px": px_col,
                "y_center_px": px_row,
                "x_center_norm": float(x_center_n),
                "y_center_norm": float(y_center_n),
                "radius_px": int(radius_px),
                "radius_km": float(radius_km),
                "radius_norm": float(radius_n),
                "lat_deg": lat_c,
                "lon_deg": lon_c,
            }
        )

    return labels, h, w


def write_labels(label_txt_path, label_meta_path, labels, stem, image_w, image_h):
    """
    Write:
    - .txt custom YOLO-like lines
    - .meta.json explicit metadata per crater
    """
    with open(label_txt_path, "w", encoding="utf-8") as f:
        for obj in labels:
            line = (
                f"{obj['class_id']} "
                f"{obj['x_center_norm']:.8f} {obj['y_center_norm']:.8f} "
                f"{obj['radius_norm']:.8f} "
                f"{obj['radius_px']} {obj['radius_km']:.6f}"
            )
            f.write(line + "\n")

    payload = {
        "format": "yolo_like_circle_v1",
        "image_stem": stem,
        "image_width": int(image_w),
        "image_height": int(image_h),
        "count": len(labels),
        "objects": labels,
    }
    with open(label_meta_path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2)


def plot_examples(example_items, label_dir, n_examples=3):
    """Plot and save a figure with up to n_examples annotated images."""
    if not example_items:
        print("[INFO] No labeled examples available for plotting.")
        return

    n = min(n_examples, len(example_items))
    fig, axes = plt.subplots(1, n, figsize=(6 * n, 6), squeeze=False)

    for i in range(n):
        ax = axes[0, i]
        item = example_items[i]
        img = cv2.imread(item["img_path"], cv2.IMREAD_UNCHANGED)
        if img is None:
            ax.set_title(f"{item['stem']} (image read error)")
            ax.axis("off")
            continue

        if img.dtype == np.uint16:
            img8 = (img / 256).astype(np.uint8)
        else:
            img8 = img
        if img8.ndim == 2:
            rgb = cv2.cvtColor(img8, cv2.COLOR_GRAY2RGB)
        elif img8.shape[2] == 4:
            rgb = cv2.cvtColor(img8, cv2.COLOR_BGRA2RGB)
        else:
            rgb = cv2.cvtColor(img8, cv2.COLOR_BGR2RGB)

        ax.imshow(rgb)
        ax.set_title(f"{item['stem']} ({len(item['labels'])} crateras)")
        ax.axis("off")

        for obj in item["labels"]:
            c = Circle(
                (obj["x_center_px"], obj["y_center_px"]),
                obj["radius_px"],
                fill=False,
                linewidth=1.5,
                edgecolor="cyan",
            )
            ax.add_patch(c)

    fig.tight_layout()
    out_plot = os.path.join(label_dir, "examples_3.png")
    fig.savefig(out_plot, dpi=160)
    plt.close(fig)
    print(f"[PLOT] Saved examples figure: {out_plot}")


def main():
    args = parse_args()

    batch_dir = os.path.abspath(args.batch)
    img_dir = os.path.join(batch_dir, "img")
    json_dir = os.path.join(batch_dir, "json")
    npz_dir = os.path.join(batch_dir, "npz")
    label_dir = os.path.join(batch_dir, "label")

    for d in (img_dir, json_dir, npz_dir):
        if not os.path.isdir(d):
            sys.exit(f"[ERROR] Required directory not found: {d}")
    os.makedirs(label_dir, exist_ok=True)

    if args.min_diam <= 0 or args.max_diam <= 0 or args.max_diam < args.min_diam:
        sys.exit("[ERROR] Invalid diameter range. Use --min-diam > 0 and --max-diam >= --min-diam")

    print(f"Loading crater catalogue: {args.craters}")
    craters_df = pd.read_parquet(args.craters)
    required_cols = {"x_coord", "y_coord", "diam_km"}
    missing_cols = required_cols - set(craters_df.columns)
    if missing_cols:
        sys.exit(f"[ERROR] Missing columns in crater catalogue: {sorted(missing_cols)}")
    print(f"  {len(craters_df):,} craters total")

    img_files = sorted(f for f in os.listdir(img_dir) if f.lower().endswith(".png"))
    if not img_files:
        sys.exit("[ERROR] No PNG files found in img/")

    print(f"Batch: {batch_dir}")
    print(f"Label: {label_dir}")
    print(f"Diameter filter: {args.min_diam:.1f} .. {args.max_diam:.1f} km")
    print(f"Images: {len(img_files)}")
    print()

    total_labels = 0
    processed = 0
    example_items = []

    for fname in img_files:
        stem = os.path.splitext(fname)[0]
        img_path = os.path.join(img_dir, fname)
        json_path = os.path.join(json_dir, f"{stem}.json")
        npz_path = os.path.join(npz_dir, f"{stem}.npz")

        if not os.path.isfile(json_path) or not os.path.isfile(npz_path):
            print(f"  [SKIP] {stem} — missing json/npz")
            continue

        labels, h, w = build_labels_for_image(
            img_path,
            npz_path,
            json_path,
            craters_df,
            args.class_id,
            args.min_diam,
            args.max_diam,
        )

        label_txt_path = os.path.join(label_dir, f"{stem}.txt")
        label_meta_path = os.path.join(label_dir, f"{stem}.meta.json")
        write_labels(label_txt_path, label_meta_path, labels, stem, w, h)

        print(f"  {stem} -> {len(labels)} labels")
        processed += 1
        total_labels += len(labels)

        if len(example_items) < args.examples and labels:
            example_items.append({
                "stem": stem,
                "img_path": img_path,
                "labels": labels,
            })

    print()
    print(f"=== Labels done: {processed} imagens, {total_labels} crateras rotuladas ===")

    plot_examples(example_items, label_dir, n_examples=args.examples)


if __name__ == "__main__":
    main()
